#!/usr/bin/env python3
"""Build a traceable narrative from recorded experiments; never fit/promote."""
import argparse
import json
from pathlib import Path


def pct(v):
    return "—" if v is None else f"{v * 100:.2f}%"


def pp(v):
    return "—" if v is None else f"{v * 100:.3f}"


def table(headers, rows):
    return "| " + " | ".join(headers) + " |\n|" + "|".join("---" for _ in headers) + "|\n" + "\n".join("| " + " | ".join(map(str, row)) + " |" for row in rows) + "\n"


def main(out):
    read = lambda name: json.loads((out / name).read_text())
    results, legacy, manifest = read("results.json"), read("legacy_reproduction.json"), read("manifest.json")
    production, distributions = read("production_status.json"), read("target_distributions.json")
    sections = []
    add = sections.append
    add("# Ons altın tahmin sistemi — uçtan uca denetim\n\nRapor: 6 Eylül 2026. Kod düzeltmeleri yereldir; canlı servis ve aktif model değiştirilmedi.\n")
    add("""## CURRENT ARCHITECTURE

Önce salt okunur inceleme tamamlandı ve kritik bulgular kullanıcıya açıklandı; uygulama bundan sonra başladı. Bu rapor **üç farklı şeyi ayırır**: canlı artifact'ın eski raporlanan metriği, aynı snapshot'ta eski eğitim reçetesinin yeniden üretimi ve bağımsız kalibrasyonlu yeni deneyler. Bunlar aynı modelin aynı protokolle ölçümü değildir.

```text
xaus günlük OHLC / Yahoo GC=F fallback + FRED son revize seriler
  → parse/normalize → 8 teknik + 11 makro → günlük CSV
  → t+h takvim günü veya sonraki ilk kapanışa simple-return target
  → her vade için expanding walk-forward → scaler → 3 küçük MLP
  → seed ortalaması → calibration weight → beklenen getiri
  → tarihsel hata quantile × volatilite ölçeği → API
  → React grafik/kartlar; ayrıca canlı Harem fiyatı ve kullanıcı senaryoları
```

Kod haritası: `app/services/xau_dataset_service.py` veri/feature/target; `feature_service.py` son vektör; `trainer.py` eğitim/artifact; `model_service.py` yükleme/scaler/ağ/interval; `prediction_service.py` API sözleşmesi; `automatic_learning_service.py` saatlik veri yenileme/eğitim kararı; `learning_service.py` elle eğitim/metrikler; `app/controllers/*` endpoint'ler. Dataset `data/xauusd_training_5y.csv`, artifact joblib + JSON, aktif işaretçi `models/active.json`. Gateway istekleri model servise iletir; market-data servisi ayrı canlı fiyat/tarihçe sağlar. FE akışı `services/api/model.ts → useForecastModel → DashboardContext → ForecastChart/ForecastCards/ScorecardSection`.

Ağ her vade için ayrı: **19 → 8 → 4 → 1**, tanh, 201 parametre/ağ; seed 17/42/91, toplam 603 parametre/vade. L2 alpha=0.08; L1/dropout yok; L-BFGS, max_iter=600 (epoch değil); erken durdurma yok. L-BFGS'de batch-size ve öğrenme hızı ayarları SGD/Adam anlamında kullanılmaz. Küçük veri üzerinde derin ağ eklemek için kanıt yok. Seed ensemble aynı mimarinin üç başlangıcıdır; üç bağımsız bilgi kaynağı değildir.

Eğitim kodu geçmiş fiyatlardan gelecekteki **getiriyi** öğrenir; gelecekteki bütün makro parametreleri bilerek o günün fiyatını çözen nedensel bir fonksiyon değildir. Feature importance veya senaryo oynatmak da nedensellik kanıtı değildir.
""")
    add(f"Ölçüm snapshot'ı: {manifest['rows']} satır, {manifest['start']}–{manifest['end']}; SHA256 `{manifest['dataset_hash']}`. Kod commit `{manifest['git_commit']}`; değişen evaluator dosyasının ayrıca SHA256'ı [manifest](manifest.json) içinde. Aktif yerel servisin yenilediği asıl CSV geri alınmadı; bütün karşılaştırmalar [donmuş kopya](dataset_snapshot.csv) üzerinde yapıldı.\n")
    add("""## CRITICAL ISSUES

| Severity | Kanıt / sorun | Yapılan / kalan |
|---|---|---|
| CRITICAL | FRED `observation_date` gerçek yayın tarihi sanılıyor. CPI referans ayı sonradan açıklanır; H.10 günlük geniş dolar verileri sonraki haftalık yayında gelir. | Yayın/vintage zamanlı offline as-of builder ve testler eklendi. **Mevcut 5 yıllık CSV onarılmış PIT veri değildir**; doğrulanmamış kaynakla model terfisi engellenir. |
| CRITICAL | Son revize makro tarihçe geçmişte bilinen değer gibi kullanılıyor. | Kaynak/vintage belirsizliği manifest'te açık; eski seriyi keyfi geciktirmek kesin çözüm diye sunulmadı. |
| HIGH | Yahoo `GC=F` gold futures fallback, spot XAU/USD ile aynı araç gibi yorumlanıyor. Eski CSV kaynak saklamıyor. | Yeni kaynak manifesti futures proxy bilgisini taşır; doğrulanmış spot sayılmaz. Mevcut tarihçenin spot olduğu kanıtlanamaz. |
| HIGH | Eski ağırlık slope'u bütün OOF etiketlerine fit edilip **aynı etiketlerde** başarı raporlanıyor. | Base fit → purged weight-cal → purged interval-cal → dış test ayrıldı. Eski skorlar bağımsız test olarak sunulmuyor. |
| HIGH | Eğitim yalnız standardize, serving ±6σ clip + sabit makroları 0 yapıyor. Aylık CPI normalde sabit kalabilir. | Yeni artifact için ortak scaler/clip; legacy sayısal davranış uyum için korunur. Replay deneyi var. |
| HIGH | Backend hata quantile'ı %80 iken FE %70 bandı etiketi kullanıyor. Volatilite ölçeklemesi sonrası gerçek kapsam bilinmiyor. | Nominal %80 metadata/etiket; ampirik kapsam yoksa doğrulanmış gibi gösterilmez. 50/70/80/90 ölçümleri ayrı üretildi. |
| HIGH | Rolling 5y veri satır sayısı aynı kalınca satır-adedi temelli retrain tetiklenmiyor; eski akış aday modeli otomatik aktifleştiriyor. | Olgunlaşan label tarihleri/hash ile aday eğitim; otomatik promotion kapalı, eski champion korunur. |
| HIGH | Eğitim endpoint'i halka açık ve yetkisiz tetiklenebilir; CPU/disk ve model bütünlüğü riski. | Admin token doğrulaması; güvenli varsayılan. Endpoint canlıda denenmedi/değiştirilmedi. |
| MEDIUM | CPI `t-365` leap-year ay sonunda yanlış referans ayını seçiyor; ilk snapshot'ta 8 örnek. | Exact-month CPI yeni PIT yolunda; legacy ölçüm reçetesi sessizce yeniden yazılmadı. |
| MEDIUM | Tarih/sayı doğrulaması, atomik dosya yazımı, snapshot lineage yetersiz. | Sonlu sayı, pozitif OHLC, sıralı/tekil tarih, target maturity, hash ve atomik replacement testleri. |
| MEDIUM | FE her canlı tick'te sabit beklenen getiriyi yeni fiyata bağlayarak verilmiş tahmini değiştiriyor. | Tahminin baz fiyatı/zamanı ayrı snapshot; client senaryosu resmi performanstan ayrılır. |
| MEDIUM | Gerçek üretim tahmin defteri ve gerçekleşen sonuçlarla bağımsız karne yok. | Opt-in immutable ledger + ayrı outcomes + 30/90 monitoring altyapısı. Gerçek PIT veri ve operasyonel reconciliation olmadan geçmiş production başarısı uydurulmaz. |
| LOW | “DXY”, RSI/ATR tanımı, gün/bar ve skill adı belirsiz. | Gerçek formüller ve birimler audit'te; eski `skill_vs_zero` MSE tabanlıdır, MAE skill ayrı. |

Doğru bilgi koşulu **`information_available_time <= prediction_time`**; istekteki eşitsizlik ters yazılmıştı. Geriye doğru observation as-of fill, ileri tarihli gözlem kullanmasa bile henüz açıklanmamış gözlemi kullanabilir. [Federal Reserve H.10](https://www.federalreserve.gov/Releases/h10/default.htm), [FRED real-time periods](https://fred.stlouisfed.org/docs/api/fred/realtime_period.html), [BLS seasonal adjustment](https://www.bls.gov/cpi/seasonal-adjustment/) bunu destekler. Spot–futures basis farkı getiriye geçince otomatik yok olmaz. [CME açıklaması](https://www.cmegroup.com/articles/case-study/case-study-hedging-risk-with-gold-futures-and-options.html).

İşlem takvimi olmadan tatil/hafta sonu aralığına “eksik işlem günü” demek, aylık CPI değişmedi diye “stale” demek doğru değil. Gerçek yayın tarihi/yaş takibi için kaynak metadata'sı gerekir. Bu sınırlamalar çözülmüş gibi işaretlenmedi.
""")
    add("## CURRENT PERFORMANCE\n\nCanlı servisten **yalnız GET** ile alınan durum; üretim gerçekleşen-tahmin karnesi değil, artifact'ın eski doğrulama metriğidir. Ayrı snapshot/model olduğu için aşağıdaki araştırma tablosuyla doğrudan performans artışı hesaplanamaz.\n")
    prod = production['responses']['/model-service/v1/learning/metrics']['body']
    add(f"Kayıt zamanı `{production['captured_at']}`, model `{prod['active_model']}`. [Ham yanıtlar](production_status.json).\n")
    add(table(["Vade", "MAE (getiri yp)", "RMSE (yp)", "Yön", "MSE skill", "Ağırlık", "OOF n"], [[h, pp(m['mae']), pp(m['rmse']), pct(m['direction']), pct(m['skill_vs_zero']), f"{m['weight']:.3f}", m['oof_rows']] for h,m in prod['metrics'].items()]))
    add("Bağımsız yeni protokol: 3 expanding dış blok (başlangıç %55/%70/%85), gerçek hedef olgunlaşma tarihine göre purge, dış blok öncesi 126 satır kalibrasyon; önce ağırlık, daha sonra hedef pencereleri çakışmayan residual kalibrasyon. Standardizasyon/imputation/rejim eşikleri train-only. MLP/ağaç adayları blok başında fit, blok içinde sabit; historical/rolling baseline yalnız o ana kadar olgunlaşmış etiketlerle günlük güncellenir. Bu cadence farkı raporlanır. Random split/KFold yok.\n\n**CSV'nin makro yayın/vintage ve spot kaynak geçmişi doğrulanmadığından, aşağıdaki “OOS” model-fit/kalibrasyon açısından dış örneklemdir; uçtan uca gerçek PIT alpha kanıtı değildir.**\n")
    add(table(["Yeni nested MLP", "n", "MAE yp", "RMSE yp", "Yön", "Sıfır dışı görüş oranı", "MAE skill", "Fiyat MAE ($)", "±2$ isabet"], [[h,m['n'],pp(m['mae']),pp(m['rmse']),pct(m['direction']),pct(m['active_fraction']),pct(m['mae_skill']),f"{m['price_mae_usd']:.2f}",pct(m['within_2_usd'])] for h,v in results.items() for m in [v['mlp_nested']['metrics']]]))
    add("Yön yalnız sıfırdan farklı tahminlerde ve sıfır olmayan actual'da ölçülür. 30 günlük %77,84 değer **günlerin sadece yaklaşık üçte birinde** görüş verilmesine aittir; tüm günlerde bu doğruluk iddiası değildir. Araştırma görüş ölçütü sıfırdan farklı getiri, uygulama kullanıcı arayüzü ölçütü weight≥0.2'dir; karıştırılmamalı. Persistence yönü `null`; ±2 yüzde puanı, **±2 dolar değildir**. Getiri MAPE sıfıra yakın hedeflerde anlamsız olduğundan kullanılmadı.\n")
    add("## BASELINE COMPARISON\n\nMAE skill = `1 − MAE_model / MAE_zero_return`; pozitif iyi. Historical majority yön baseline'ına eğitimde bilinen mutlak getirinin medyanı büyüklük olarak eklenmiştir; saf yön başarısı ile fiyat kalibrasyonu ayrı yorumlanır.\n")
    names = ('persistence','historical_mean','rolling_mean_126','momentum_20d','direction_majority','linear','ridge','elasticnet','random_forest','gradient_boosting','mlp_raw','mlp_nested','direction_logistic','heterogeneous_calibrated')
    add(table(["Model", "7d MAE yp / skill", "14d MAE yp / skill", "30d MAE yp / skill"], [[name,*[f"{pp(results[h][name]['metrics']['mae'])} / {pct(results[h][name]['metrics']['mae_skill'])}" for h in results]] for name in names]))
    add("Her dış örneklemde always-up yön doğruluğu 7d %61,45, 14d %62,80, 30d %69,19. 14d ham MLP %57,57 ile drift benchmark'ını aşmıyor. Sadece eski kalibre %62,43'e bakıp güçlü parametre öğrenimi demek desteklenmiyor. Son fold'da majority baseline bile 14d negatif skill gösteriyor; bu da rejim istikrarının önemini ortaya koyuyor.\n")
    add(table(["Aday", "Vade", "Fold MAE skill (1 / 2 / 3)", "Toplam MAE skill %95 block-CI"], [[name,h,' / '.join(pct(f['mae_skill']) for f in results[h][name]['folds']),' – '.join(pct(x) for x in results[h][name]['confidence_intervals95']['mae_skill'])] for name in ('direction_majority','ridge_macro','mlp_nested','direction_logistic') for h in results]))
    add("Güven aralıkları bağımlılığı kısmen koruyan 30 gözlemlik moving-block bootstrap (500 tekrar); model ile majority farkında eşleştirilmiş 1000 tekrar var. [Paired sonuçlar](paired_comparisons.json). Bunlar aynı snapshot'a koşullu, çoklu deneme düzeltmesi ve yeni bağımsız seçim holdout'u değildir; 129 sonuçtan en iyiyi seçip garanti verilemez.\n")
    add("## FEATURE AUDIT\n\n19 feature'ın kaynak/formül/lookback/yayın/missing/leakage tablosu [FEATURE_AUDIT.md](../../docs/model-audit/FEATURE_AUDIT.md) içinde. Teknik pencereler çoğunlukla **bar**, makro pencereler **takvim günü**. Dolar sütunu `DTWEXBGS`, ICE DXY değil. Core CPI seasonally-adjusted `CPILFESL`; breakeven doğrudan seri değil DGS10−DFII10 spread'i. ATR için bağımsız yeniden hesaplamaya gerekli ham H/L mevcut CSV'de yok.\n")
    redundancy = read('feature_redundancy.json')
    pairs = sorted([(abs(redundancy['spearman'][i][j]), redundancy['features'][i], redundancy['features'][j], redundancy['spearman'][i][j]) for i in range(19) for j in range(i+1,19)], reverse=True)[:6]
    add(table(["Feature 1", "Feature 2", "Spearman"], [[a,b,f"{c:.3f}"] for _,a,b,c in pairs]))
    add("Pearson/Spearman tüm snapshot'ta **betimleyici**, feature seçimi için kullanılmadı; MI ilk %50 etiketli bölümde hesaplandı. [Matrisler ve MI](feature_redundancy.json). Her 19 feature için Ridge ve nested MLP'de dış-fold 20-bar blok permutation (3 tekrar) `results.json` içinde. Korelasyonlu özellikleri tek tek bozmak ortak yapıdan uzak senaryolar yaratabilir; önem nedensellik değildir. 7d nested modelin ağırlığı sıfır olduğu için permutation önemleri sıfır; buradan ham özellikler hiçbir bilgi taşımıyor sonucu çıkarılmaz.\n")
    add(table(["Feature deneyi", "7d skill", "14d skill", "30d skill"], [[name,*[pct(results[h][name]['metrics']['mae_skill']) for h in results]] for name in ('mlp_nested','mlp_technical','mlp_macro','mlp_regime','mlp_minus_dollar','mlp_minus_real_yield','mlp_minus_inflation','mlp_minus_vix','mlp_minus_oil','mlp_minus_momentum','mlp_minus_volatility','mlp_macro_lag_stress','mlp_engineered','mlp_lookback_10_20_40')]))
    add("Ridge macro bazı ortalamalarda iyi olsa da bu **en kritik yayın/vintage sorunu olan grup**. Katkı doğrulanmış sayılamaz. Yeni teknik adaylar SMA20/100/200, EMA/trend slope, z-score, percentile, RSI slope, MACD, momentum acceleration, volatilite oranları ve 10/20/40 pencereleridir. Macro-lag stress CPI45/dolar10/diğer2 takvim günü kaydırma deneyidir; gerçek yayın takviminin yerine geçen bir leakage düzeltmesi değildir. Özellikler sırf teorik makullükle canlı modele eklenmedi.\n\nMacro LEVEL+CHANGE+Z-SCORE, cross-asset ve event-proximity güvenilir ham/PIT seri olmadığı için üretilemedi; mevcut değişimlerden gerçek seviyeler icat edilmedi. SHAP ek bağımlılığı yerine OOF blok permutation kullanıldı.\n")
    add("## REGIME ANALYSIS\n\nRejim eşikleri yalnız train'de: volatilite 1/3–2/3 quantile; real yield/dolar20 değişim işareti; SMA50 mesafesi ±%2 bull/bear; VIX>20 risk-off. Bunlar tanımlı araştırma grupları, otomatik işlem veya nedensel rejim etiketleri değil. Aşağıda **ham MLP** seçildi; kalibrasyonun sıfır-görüş etkisi gizlenmiyor.\n")
    add(table(["Rejim", "7d n / skill", "14d n / skill", "30d n / skill"], [[regime,*[f"{results[h]['mlp_raw']['regimes'][regime]['n']} / {pct(results[h]['mlp_raw']['regimes'][regime]['mae_skill'])}" for h in results]] for regime in ('high_vol','low_vol','rising_real_yield','falling_real_yield','strong_dollar','weak_dollar','bull','bear','risk_off','risk_on')]))
    add("30d ham MLP güçlü dolar grubunda daha iyi, zayıf dolarda belirgin daha kötü; yüksek volatilitede edge yok. Küçük/dependent alt örneklemler ve makro PIT belirsizliği nedeniyle bu gözlemden production regime gate seçilmedi. Regime feature eklemek OOS'ta tutarlı kazanç sağlamadığı için Mixture of Experts'e geçilmedi.\n\n14d için sorun sadece kapasite değil: legacy calibration iyimserliği, target overlap, zayıf yön bilgisi, rejim kararsızlığı ve serving skew birlikte gözleniyor. 10/20/40 lookback, recency, 3y/5y, Ridge/GBR/ensemble denendi; drift baseline'ına karşı sağlam artış kanıtlanmadı. “Daha çok nöron çözer” iddiası desteklenmedi. Ayrı nedensel olarak her hatanın payı bu veriyle ölçülemez.\n")
    add("## UNCERTAINTY CALIBRATION\n\nAşağıda nested MLP'nin **gerçek dış test kapsamı** var. Aynı testte weight optimize edilmedi. Rolling126 yalnız o tahmin anından önce olgunlaşmış residual'ları tüketir. Adaptive deney, gecikmeli sonuç başına bir kez alpha günceller (gamma .01, alpha .01–.99); özgün ACI'nin koşulsuz garantisini bu uygulamaya taşımıyoruz. [ACI makalesi](https://arxiv.org/abs/2106.00170).\n")
    add(table(["Vade", "Nominal", "Split", "Vol-normalized", "Rolling126", "Adaptive"], [[h,pct(c),*[pct(v['mlp_nested']['intervals'][f'{method}_{c}']['empirical']) for method in ('split','volnorm','rolling','adaptive')]] for h,v in results.items() for c in (.5,.7,.8,.9)]))
    add("Adaptive kapsam çoğu seviyede nominale yaklaşıyor; bu tek başına kazanmak değildir: bant genişliği ve interval-score da `results.json` içinde, daha geniş bantla yapay başarı kontrol edilebilir. **Canlı interval algoritması değiştirilmedi**; yanlış nominal etiket ve metadata düzeltildi. Gerçek PIT forward sonuçları olmadan daha iyi kalibre edilmiş production model ilan edilmedi.\n\n![Kalibrasyon eğrileri](calibration.svg)\n")
    add("## EXPERIMENT RESULTS\n\n43 önceden tanımlı aday × 3 vade = **129 karşılaştırma**, her biri 3 kronolojik dış fold. Tüm sonuçlar, olumsuzlar dahil [EXPERIMENTS.md](EXPERIMENTS.md); parametre/seed/validation tanımları [manifest.json](manifest.json), metrik/fold/rejim/CI/importance/top20 [results.json](results.json), her dış tahmin [oos_predictions.csv](oos_predictions.csv). Convergence warning'ler [ayrı kaydedildi](convergence_warnings.json); sonuçlar sessizce başarılı yakınsama gibi işaretlenmedi.\n")
    add(table(["Target", "n", "Mean yp", "Median yp", "Std yp", "Skew", "Excess kurtosis", "Min yp", "Max yp"], [[h,d['n'],pp(d['mean']),pp(d['median']),pp(d['std']),f"{d['skew']:.3f}",f"{d['excess_kurtosis']:.3f}",pp(d['min']),pp(d['max'])] for h,d in distributions.items()]))
    add(table(["Hedef/loss/window deneyi", "7d MAE yp", "14d MAE yp", "30d MAE yp"], [[name,*[pp(results[h][name]['metrics']['mae']) for h in results]] for name in ('mlp_nested','mlp_log_target','mlp_price_target','mlp_winsor_train_only','boosting_huber','boosting_mae','mlp_rolling3y','mlp_rolling5y','mlp_recency_1y','mlp_shrinkage_calibration','mlp_rolling_calibration')]))
    add("Log hedef simple return'den tutarlı üstün değil. Raw future price hedefi yalnız train'de standardize edildi fakat calibration sonrası görüş yok; return hedefini korumak bu deneyde daha makul. Winsor train-only %1/%99: 30d ortalama biraz iyileşti, fakat sağlam seçim kanıtı değil. Huber/MAE loss GBR'de test edildi; bunları MLP-loss denemesi olarak sunmuyoruz. Classification-only logistic denendi; fiyat büyüklüğü train medyanıyla ölçekli surrogate, calibrated probability iddiası yok. Heterogeneous ensemble Ridge+GBR+MLP ağırlıkları erken calibration'da nonnegative/sum=1 optimize edildi; dış testte ağırlık seçilmedi.\n\n3y/5y aynı sonuç çıkabildi: toplam geçmiş zaten yaklaşık beş yıl ve train/cal ayrımı nedeniyle bazı fold'larda pencereler aynı örnekleri içeriyor. Bu, başka uzun tarihçelerde pencere etkisizdir demek değildir. Recency yarı ömrü önceden 365 gün seçildi, testte optimize edilmedi.\n\nOOD için train-only Ledoit–Wolf Mahalanobis ve ±6σ; no-view için |getiri|≥0.25σ araştırma maskeleri var. Threshold'lar dış örneklemde kazanan eşik olarak kalibre edilmedi; production'da yeni gate olarak devreye alınmadı. Model skill, büyüklük, belirsizlik, disagreement ayrı kavramlar olarak tutulur.\n\n**Top20 hata analizi:** Her vade için nested/replay/Ridge/ensemble tabloları ayrı artifact'ta. Yakın tarihlerdeki birçok büyük hata aynı örtüşen target hareketini temsil edebilir; 20 bağımsız olay değildir. CPI/FOMC/jeopolitik haber gibi nedenler doğrulanmış geçmiş event takvimi olmadığından etiketlenmedi.\n")
    add(table(["Vade", "Prediction → target", "Tahmin yp", "Gerçek yp", "Mutlak hata $", "VIX", "USD20", "Real20 pp"], [[h,f"{e['date']} → {e['target_date']}",pp(e['predicted_return']),pp(e['actual_return']),f"{e['absolute_error_usd']:.2f}",e['vix'],pct(e['broad_dollar_return20']),f"{e['real_yield_change20']:.3f}"] for h,v in results.items() for e in v['mlp_nested']['largest_errors'][:3]]))
    add("## BEST MODEL\n\n**Yeni production kazananı yok.** Tutarlı fold/rejim artışı, drift benchmark'ına ek bilgi, doğru kapsam ve doğrulanmış PIT veri şartları birlikte sağlanmadı.\n")
    add(table(["Vade", "Öneri"], [["7d", "No-view korunmalı. Basit drift/Ridge macro yalnız araştırma benchmark'ı; PIT doğrulanmadan terfi yok."],["14d", "Görüş üretmeye zorlama. Yön/MAE drift benchmark'ına karşı bağımsız kanıt bekle; mimari büyütme yok."],["30d", "Mevcut artifact korunmalı; kazanımı doğrulanmış varsayma. Basit majority/mean ve logistic challenger ile aynı PIT forward testte kıyasla."]]))
    add("## CHANGES IMPLEMENTED\n\nPhase 1: salt okunur mimari/feature audit tamamlandı. Phase 2: doğruluk bariyerleri ve testleri uygulandı; gerçek PIT kaynak temini **tamamlanmadı**. Phase 3–5: ortak snapshot'ta baselines/features/models deneyleri çalıştırıldı. Phase 6: calibration/coverage araştırması ve dürüst API etiketi; interval replacement yok. Phase 7: yerel ledger/monitoring altyapısı; canlıya devreye alma ve gerçekleşmiş forward karne **tamamlanmadı**.\n\n- Veri: `data_quality.py`, `point_in_time.py`, `xau_dataset_service.py`, `feature_service.py`; canonical 19-vector, finite/OHLC/order kontrolü, atomic CSV+hash manifest, kaynak/vintage açıklığı.\n- Eğitim: `preprocessing.py`, `temporal_validation.py`, `trainer.py`, `automatic_learning_service.py`; label-date purge, train/serve clip parity, ayrı calibration, reproducibility ve aday-only eğitim.\n- Serving: `model_service.py`, `prediction_service.py`, `prediction_ledger.py`, `api_models.py`, `config.py`, controller/auth, `learning_service.py`; eski artifact sayısal uyumu, status/OOD/interval metadata, immutable kayıt ve ölçüm ayrımı.\n- FE: API model/metrics parser, domain types/predict, dashboard model/snapshot context, chart/forecast cards/scorecard; baz-fiyat sabitleme, nominal band bilgisi, no-view satırlarının korunması. Tasarım dili/layout yeniden yapılmadı.\n- Deney: `research/evaluation.py`, `scripts/run_model_audit.py`, `summarize_model_audit.py`, `render_model_audit_report.py`, `capture_production_status.py`; testler ve bu rapor.\n\n[Operasyon ve kalan aktivasyon adımları](../../docs/model-audit/OPERATIONS.md). [Doğrulama sonuçları](VERIFICATION.md). Bu yerel değişiklikler commit/push/deploy edilmedi; mevcut CSV'deki çalışan servis kaynaklı fark korundu.\n")
    add("## BEFORE / AFTER\n\nAynı donmuş dataset, **eski kusurlu global OOF calibration reçetesi** ile yeni nested araştırma protokolü. “After” doğrulama doğruluğudur; aynı kalibrasyon pencere uzunluğu/finalfit politikasını kullanan bir hiperparametre A/B kazancı değildir. Ayrıca bu tablo canlı artifact'ın skorlarıyla karıştırılmamalı. Yeni servis trainer adayının ayrı metadata/sonuçları aday raporundadır.\n")
    add(table(["Vade", "Old → new MAE yp", "Old → new yön", "New görüş oranı", "Old → new MAE skill", "Old → new MSE skill"], [[h,f"{pp(legacy[h]['reported']['mae'])} → {pp(v['mlp_nested']['metrics']['mae'])}",f"{pct(legacy[h]['reported']['direction'])} → {pct(v['mlp_nested']['metrics']['direction'])}",pct(v['mlp_nested']['metrics']['active_fraction']),f"{pct(legacy[h]['reported']['mae_skill'])} → {pct(v['mlp_nested']['metrics']['mae_skill'])}",f"{pct(legacy[h]['reported']['mse_skill'])} → {pct(v['mlp_nested']['metrics']['mse_skill'])}"] for h,v in results.items()]))
    add("Eski 30d skorunun düşmesi üretimde modeli bozduğumuz anlamına gelmez: canlı artifact değiştirilmedi. Bağımsız kalibrasyon, eğitim boyutu ve etkin görüş günleri değiştiği için daha dürüst ölçüm aynı yüksek skoru garanti etmez. 14d araştırma MAE'si küçük iyileşse de baseline/fold/rejim şartlarını karşılamadığı için terfi yapılmadı.\n")
    candidate = read('candidate/xauusd_candidate_checked.json')
    add(f"### Gerçek servis trainer'ıyla sıfırdan eğitilen aday\n\nAday `{candidate['version']}` aynı snapshot'ta gerçek `trainer.train_model` ile max_iter=600 çalıştırılarak üretildi; schema ve champion korunumu doğrulandı. Bu trainer kalibrasyona geçmişin %20'sini ayırır ve weight/residual bölümü %60/%40'tır; araştırmadaki sabit126 ve yarı-yarı bölümlerle aynı deney değildir. **Uygulanan eğitim düzeltmelerinin esas before/after sonucu aşağıdadır.** [Aday artifact ve ayrıntılar](candidate/README.md).\n")
    add(table(["Vade", "Old → candidate MAE yp", "Old → candidate MAE skill", "Candidate yön", "Candidate görüş oranı", "Nominal80 gerçek kapsam", "Final weight"], [[h,f"{pp(legacy[h]['reported']['mae'])} → {pp(m['mae'])}",f"{pct(legacy[h]['reported']['mae_skill'])} → {pct(m['mae_skill_vs_zero'])}",pct(m['direction']),pct(m['active_fraction']),pct(m['empirical_coverage']['0.8']),f"{m['weight']:.4f}"] for h,m in candidate['metrics'].items()]))
    add("Bu tabloda yön yalnız weight≥0.2 olan sıfır-olmayan görüşlerde; final weight ise bütün mevcut geçmişten gelecek tahmin için kalibre edilen ayrı değerdir. 7/14 final aday no-view; 30 final aday görüş verebilir fakat dış-test kazanımı ve band kapsamı terfi için yeterli değildir. Yeniden eğitim yapıldı; aktif modele entegrasyon kodu hazır, **artifact aktivasyonu yapılmadı**.\n")
    add("## REJECTED IDEAS\n\n- **Bu deneyde terfi reddedildi:** büyük feature seti, raw-price target, heterojen ensemble, log target, Huber/MAE GBR, lookback değişimi ve recency. Bazısı tek ortalamada iyi; ortak istikrar şartlarını sağlamıyor. Ayrıntılar tüm-deney tablosunda.\n- **Performansla reddedilmiş değil, çalıştırılmadı:** ortak magnitude+direction multi-head ağı, Bayesian calibration, inverse-error ensemble, SHAP, optimizasyonlu OOD gate. Mevcut doğruluk/veri problemleri çözülmeden ilave karmaşıklığın production değeri kanıtlanamaz; classification-only ve nested constrained ensemble daha basit karşılaştırma olarak çalıştırıldı.\n- **Güvenilir veri olmadığı için ertelendi:** macro-level/zscore, silver/copper/S&P/treasury-vol, geçmiş event proximity, gerçek vintage backtest. Bunlar veri yokken sentetik etiket/seri üretmeyerek bırakıldı.\n- **İlkesel olarak reddedildi:** random split, test etiketleriyle calibrate edip aynı testi başarı diye sunmak, güncel revize seriye “PIT” demek, %70 etiketiyle %80 quantile göstermek, 30d'yi toplam skor adına değiştirmek, yeni adayı otomatik canlıya geçirmek, ±2$ garanti etmek.\n")
    add("## FINAL RECOMMENDATION\n\nÖncelik yeni ağ değil, **doğrulanmış spot + yayın/vintage verisi ve bağımsız forward ölçüm**. Yalnız veri çoğaltmak veya nöron eklemek bu eksikliği gidermez.\n\n1. Tek bir spot XAU/USD kapanış sağlayıcısı/session seç; ham OHLC, source, instrument, completed_at ve değişmeyen snapshot hash'lerini arşivle. Futures proxy'yi spot başarı karnesine katma.\n2. Makro gözlem tarihi yanında gerçek available_at/vintage sakla; CPI önceki yıl aynı referans ayı. FRED/ALFRED geçmiş release/vintage erişimi ve provider lisansı gerektiğinde temin edilmeli. [FRED vintage dates](https://fred.stlouisfed.org/docs/api/fred/series_vintagedates.html). Yeni builder'dan gerçek PIT dataset'i yeniden üret.\n3. Bu rapordaki aynı chronological deneyleri PIT snapshot'ta tekrar çalıştır; seçimde görülmemiş yeni dönem üzerinde teyit et. Horizon bazında baseline skill + direction + fold/rejim tutarlılığı + coverage/width koşullarını birlikte değerlendir.\n4. Mevcut 30d artifact'ı koru; 7/14d no-view yeteneğini koru. Tahminleri tek baz-fiyat/timestamp ile immutable kaydet; doğrulanmış aynı kaynak kapanışlarıyla target sonrası uzlaştır; 30/90 gerçek forward karne dolmadan başarı ilan etme.\n5. Düzeltmeleri test/staging sonrası ayrı bir deployment adımıyla al. Model terfisi ayrı, açık operatör kararı olmalı; bu çalışma hiçbir adayı canlıya almadı.\n\nSonuç: mevcut veriyle parametrelerin yeni piyasa koşullarında güvenilir fiyat ürettiğini veya ±2$ hassasiyeti sağladığını kanıtlayamıyoruz. Buna karşın veri ve ölçüm hataları somutlaştırıldı, yanlış güven üreten yollar için bariyerler kondu ve tekrar üretilebilir karşılaştırma altyapısı çalıştırıldı.\n")
    (out/'REPORT.md').write_text('\n'.join(sections), encoding='utf-8')
    print(f"Report written: {out/'REPORT.md'}")


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('directory', type=Path)
    main(parser.parse_args().directory)
